
[sncast.ecd9396a]
account = "ecd9396a"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.f2c5910f]
account = "f2c5910f"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.2c1a4208]
account = "2c1a4208"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.2ebdee14]
account = "2ebdee14"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.36285a1f]
account = "36285a1f"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.312b1058]
account = "312b1058"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.9941d85e]
account = "9941d85e"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.3bd9eb7f]
account = "3bd9eb7f"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.9e28d54d]
account = "9e28d54d"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.d51b7564]
account = "d51b7564"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.de826d89]
account = "de826d89"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.3ff19973]
account = "3ff19973"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.4723d8d3]
account = "4723d8d3"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.a037b784]
account = "a037b784"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.29ec5d51]
account = "29ec5d51"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.b6e127b2]
account = "b6e127b2"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.a656cae6]
account = "a656cae6"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.e83fb091]
account = "e83fb091"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.8caa2c4b]
account = "8caa2c4b"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.ed21f96b]
account = "ed21f96b"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.4eab59ac]
account = "4eab59ac"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.3f5e01ae]
account = "3f5e01ae"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.7141e573]
account = "7141e573"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.dedb6d5e]
account = "dedb6d5e"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.fd24e1b5]
account = "fd24e1b5"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.92335352]
account = "92335352"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.3edec7bb]
account = "3edec7bb"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.5077d107]
account = "5077d107"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.db932a38]
account = "db932a38"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.a2b3affd]
account = "a2b3affd"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.3c002bf3]
account = "3c002bf3"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.60721b42]
account = "60721b42"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.efb82831]
account = "efb82831"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.d02880f8]
account = "d02880f8"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.a28839fc]
account = "a28839fc"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.f52a300c]
account = "f52a300c"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.04c408d2]
account = "04c408d2"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.608138a1]
account = "608138a1"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.16ae90a0]
account = "16ae90a0"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.d6e87625]
account = "d6e87625"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.08d30139]
account = "08d30139"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.e333f70a]
account = "e333f70a"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.f11e987d]
account = "f11e987d"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.d6da7ddf]
account = "d6da7ddf"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.8c45c9d8]
account = "8c45c9d8"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.c7b6b912]
account = "c7b6b912"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.72076697]
account = "72076697"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.e71d2c70]
account = "e71d2c70"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.26acb1fe]
account = "26acb1fe"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"
