
[sncast.bb43c6a4]
account = "bb43c6a4"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"

[sncast.50031e80]
account = "50031e80"
accounts-file = "/Users/kenzman/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050/rpc"
